ASPCursus3/Models/Filiaal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ASPCursus3.Models
{
    public class Filiaal
    {
        public int ID { get; set; }
        public string Naam { get; set; }
        [UIHint("sterretjes")]
        public DateTime Gebouwd { get; set; }
        public decimal Waarde { get; set; }
        public Eigenaar Eigenaar { get; set; }
    }
}

ASPCursus3/Models/HoofdZetel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASPCursus3.Models
{
    public class HoofdZetel
    {
        public string Straat { get; set; }
        public string HuisNr { get; set; }
        public string Postcode { get; set; }
        public string Gemeente { get; set; }
    }
}

ASPCursus3/Controllers/FiliaalController.cs
using ASPCursus3.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPCursus3.Models;

namespace ASPCursus3.Controllers
{
    public class FiliaalController : Controller
    {
        private FiliaalService filiaalService = new FiliaalService();
        private HoofdzetelService hoofdzetelService = new HoofdzetelService();
        // GET: Filiaal
        public ActionResult Index()
        {
            var hoofdzetel = hoofdzetelService.read();
            ViewBag.hoofdzetel = hoofdzetel;
            var filialen = filiaalService.FindAll();
            return View(filialen);
        }
        public ActionResult Verwijderen(int id)
        {
            var filiaal = filiaalService.Read(id);
            return View(filiaal);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var filiaal = filiaalService.Read(id);
            TempData["filiaal"] = filiaal;
            filiaalService.Delete(id);
            return RedirectToAction("Verwijderd");
        }
        public ActionResult Verwijderd()
        {
            var filiaal = (Filiaal)TempData["filiaal"];
            return View(filiaal);
        }
    }
}

ASPCursus3/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPCursus3.Controllers
{
    public class TimeController : Controller
    {
        // GET: Time
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public PartialViewResult ShowTime()
        {
            DateTime time = DateTime.Now;
            return PartialView(time);
        }
    }
}

ASPCursus3/Views/Filiaal/Filialen.cshtml
@model List<ASPCursus3.Models.Filiaal>
<h2>Filialen</h2>
<ul>
    @foreach(var filiaal in Model)
    {
        var url = Url.Action("Verwijderen", "Filiaal", new { ID = filiaal.ID });
        <li>@filiaal.ID @filiaal.Naam @MyHelpers.MilieuScore(filiaal.Gebouwd) @Html.DisplayFor(m=>filiaal.Gebouwd) 
            @Html.DisplayFor(m=>filiaal.Waarde) @Html.DisplayFor(m=>filiaal.Eigenaar)<a href="@url"><img src="~/Images/delete.png" alt="delete"/></a>
        </li>
    }
</ul>

ASPCursus3/Views/Filiaal/FilialenVanaf2Miljoen.cshtml
@model IEnumerable<ASPCursus3.Models.Filiaal>
<h2>Onze filialen met waarde vanaf 2 miljoen</h2>
<ul>
    @foreach(var filiaal in Model)
    {
        <li>@filiaal.ID @filiaal.Naam</li>
    }
</ul>

ASPCursus3/Views/Filiaal/Hoofdzetel.cshtml
<h2>Onze hoofdzetel</h2>
<p>straat : @ViewBag.HoofdZetel.Straat</p>
<p>Huisnr : @ViewBag.HoofdZetel.HuisNr</p>
<p>Postcode : @ViewBag.HoofdZetel.Postcode</p>
<p>Gemeente :@ViewBag.HoofdZetel.Gemeente</p>

ASPCursus3/Views/Filiaal/Index.cshtml
@model List<ASPCursus3.Models.Filiaal>

@{
    ViewBag.Title = "Index";
}
@Html.Partial("Hoofdzetel")
@Html.Partial("Filialen")
@Html.Partial("FilialenVanaf2Miljoen",Model.Where(m=>m.Waarde>=2000000))
@Html.Action("ShowTime","Time")

ASPCursus3/Views/Filiaal/Verwijderd.cshtml
@model ASPCursus3.Models.Filiaal
@{ 
    ViewBag.Title = "Verwijderd";
}
<h2>Verwijdering van @Model.Naam is doorgevoerd.</h2>
<h3>Terug naar de <a href="Index">lijst</a></h3>

ASPCursus3/Views/Filiaal/Verwijderen.cshtml
@model ASPCursus3.Models.Filiaal
@{ 
    ViewBag.Title = "verwijderen";
}
<h2>@Model.Naam verwijderen?</h2>
    <form method="post" action="../Delete/@Model.ID"><input type="submit" value="Delete" /></form>