MVC_Security/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Security.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC_Security/Controllers/LeraarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Security.Controllers
{
    [Authorize(Users ="Leraar1@mvc.net,Leraar2@mvc.net,Leraar3@mvc.net")]
    public class LeraarController : Controller
    {
        // GET: Leraar
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC_Security/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Security.Controllers
{
    [Authorize(Roles ="Student,Leraar")]
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC_Security/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Html.ActionLink("studenten","Index","Student")</h2>
        <p><a class="btn btn-default" href="~/Student">Naar de pagina voor studenten &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>@Html.ActionLink("Leraren","Index","Leraar")</h2>
        <p><a class="btn btn-default" href="~/Leraar">Naar de pagina voor leraren &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>@Html.ActionLink("User administrators", "Index", "User")</h2>
        <p><a class="btn btn-default" href="~/User">Naar de pagina voor user admins &raquo;</a></p>
    </div>
</div>
<div>
    <ul class="nav nav-pills">
        <li><a>home</a></li>
        <li><a>About</a></li>
        <li><a>Contact</a></li>
    </ul>
</div>
<div>
    <ul class="breadcrumb">
        <li><a href="#">VDAB</a></li>
        <li><a href="#">IT opleidingen</a></li>
        <li><a href="#">Ontwikkelaar met C#</a> </li>
    </ul>
</div>
<div>
    <ul class="pagination">
        <li><a href="#">Prev</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table">
            <thead>
                <tr><th>Links</th><th>Rechts</th></tr>
            </thead>
            <tbody>
                <tr><td>Linksboven</td><td>Rechtsboven</td></tr>
                <tr><td>Linksonder</td><td>Rechtsonder</td></tr>
            </tbody>
        </table>
    </div>
</div>