MVC_Bierenapplication/Models/Bier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Bierenapplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bier
    {
        public int BierNr { get; set; }
        public string Naam { get; set; }
        public int BrouwerNr { get; set; }
        public int SoortNr { get; set; }
        public Nullable<float> Alcohol { get; set; }
    
        public virtual Brouwer Brouwer { get; set; }
        public virtual Soort Soort { get; set; }
    }
}

MVC_Bierenapplication/Controllers/BierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_Bierenapplication.Models;

namespace MVC_Bierenapplication.Controllers
{
    public class BierController : Controller
    {
        private MVCBierenEntities db = new MVCBierenEntities();

        // GET: Biers
        public ActionResult Index()
        {
            var bieren = db.Bieren.Include(b => b.Brouwer).Include(b => b.Soort);
            return View(bieren.ToList());
        }

        // GET: Biers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bier bier = db.Bieren.Find(id);
            if (bier == null)
            {
                return HttpNotFound();
            }
            return View(bier);
        }
        [Authorize(Roles = "Admin")]
        // GET: Biers/Create
        public ActionResult Create()
        {
            ViewBag.BrouwerNr = new SelectList(db.Brouwers, "BrouwerNr", "BrNaam");
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam");
            return View();
        }

        // POST: Biers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BierNr,Naam,BrouwerNr,SoortNr,Alcohol")] Bier bier)
        {
            if (ModelState.IsValid)
            {
                db.Bieren.Add(bier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrouwerNr = new SelectList(db.Brouwers, "BrouwerNr", "BrNaam", bier.BrouwerNr);
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam", bier.SoortNr);
            return View(bier);
        }
        [Authorize(Roles = "Admin")]
        // GET: Biers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bier bier = db.Bieren.Find(id);
            if (bier == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrouwerNr = new SelectList(db.Brouwers, "BrouwerNr", "BrNaam", bier.BrouwerNr);
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam", bier.SoortNr);
            return View(bier);
        }

        // POST: Biers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BierNr,Naam,BrouwerNr,SoortNr,Alcohol")] Bier bier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrouwerNr = new SelectList(db.Brouwers, "BrouwerNr", "BrNaam", bier.BrouwerNr);
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam", bier.SoortNr);
            return View(bier);
        }
        [Authorize(Roles = "Admin")]
        // GET: Biers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bier bier = db.Bieren.Find(id);
            if (bier == null)
            {
                return HttpNotFound();
            }
            return View(bier);
        }

        // POST: Biers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bier bier = db.Bieren.Find(id);
            db.Bieren.Remove(bier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_Bierenapplication/Views/Bier/Create.cshtml
@model MVC_Bierenapplication.Models.Bier

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bier</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrouwerNr, "BrouwerNr", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrouwerNr", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrouwerNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoortNr, "SoortNr", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SoortNr", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoortNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alcohol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alcohol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alcohol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_Bierenapplication/Views/Bier/Delete.cshtml
@model MVC_Bierenapplication.Models.Bier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alcohol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alcohol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brouwer.BrNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brouwer.BrNaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soort.Naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soort.Naam)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC_Bierenapplication/Views/Bier/Details.cshtml
@model MVC_Bierenapplication.Models.Bier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alcohol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alcohol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brouwer.BrNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brouwer.BrNaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soort.Naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soort.Naam)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BierNr }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC_Bierenapplication/Views/Bier/Edit.cshtml
@model MVC_Bierenapplication.Models.Bier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bier</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BierNr)

        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrouwerNr, "BrouwerNr", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrouwerNr", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrouwerNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoortNr, "SoortNr", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SoortNr", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoortNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alcohol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alcohol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alcohol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_Bierenapplication/Views/Bier/Index.cshtml
@model IEnumerable<MVC_Bierenapplication.Models.Bier>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create","Bier",null,new { @class="btn btn-default"})
    @Html.ActionLink("Terug naar Home","Index","Home",null,new { @class="btn btn-default"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Alcohol)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brouwer.BrNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Soort.Naam)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Naam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Alcohol)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brouwer.BrNaam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Soort.Naam)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BierNr }) |
            @Html.ActionLink("Details", "Details", new { id=item.BierNr }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BierNr })
        </td>
    </tr>
}

</table>